version: '3.8'

services:
  rf-server:
    build: .
    ports:
      - "50051:50051"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; ch = grpc.insecure_channel('localhost:50051'); grpc.channel_ready_future(ch).result(timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a monitoring service
  rf-monitor:
    build: .
    command: python client.py status usrp0
    depends_on:
      - rf-server
    profiles:
      - monitoring
    restart: "no"

volumes:
  logs: